// Generated by CoffeeScript 1.8.0
(function() {
  var CHR, MULTIMIX, TEX, THIS, TRM, alert, badge, debug, echo, help, info, log, njs_fs, njs_path, read, route_of_postscript, route_of_preamble, rpr, warn, whisper;

  TRM = require('coffeenode-trm');

  rpr = TRM.rpr.bind(TRM);

  badge = 'XLTX';

  log = TRM.get_logger('plain', badge);

  info = TRM.get_logger('info', badge);

  whisper = TRM.get_logger('whisper', badge);

  alert = TRM.get_logger('alert', badge);

  debug = TRM.get_logger('debug', badge);

  warn = TRM.get_logger('warn', badge);

  help = TRM.get_logger('help', badge);

  echo = TRM.echo.bind(TRM);

  njs_fs = require('fs');

  njs_path = require('path');

  TRM = require('coffeenode-trm');

  CHR = require('coffeenode-chr');

  read = function(route) {
    return njs_fs.readFileSync(njs_path.join(__dirname, route), 'utf-8');
  };

  TEX = require('coffeenode-tex');

  route_of_preamble = '../tex-inputs/jzr2014-preamble.tex';

  route_of_postscript = '../tex-inputs/jzr2014-postscript.tex';

  this.glyph_tag_by_rsg = {
    'u-cjk': TEX.make_command('cn'),
    'u-cjk-xa': TEX.make_command('cnxa'),
    'u-cjk-xb': TEX.make_command('cnxb'),
    'u-cjk-xc': TEX.make_command('cnxc'),
    'u-cjk-xd': TEX.make_command('cnxd'),
    'u-cjk-cmpi1': TEX.make_command('cncone'),
    'u-cjk-cmpi2': TEX.make_command('cnctwo'),
    'u-cjk-rad1': TEX.make_command('cnrone'),
    'u-cjk-rad2': TEX.make_command('cnrtwo'),
    'u-cjk-sym': TEX.make_command('cnsym'),
    'u-cjk-strk': TEX.make_command('cnstrk'),
    'u-pua': TEX.make_command('cnjzr'),
    'jzr-fig': TEX.make_command('cnjzr'),

    /* TAINT kludge to accommodate for the fact that Sun-ExtA is missing a few characters: */
    'xxx': TEX.make_command('cnextra')
  };

  this.stacked_fncr = TEX.make_multicommand('fncr', 2);

  this._py = TEX.make_command('py');

  this.ka = TEX.make_command('ka');

  this.hi = TEX.make_command('hi');

  this.hg = TEX.make_command('hg');

  this.gloss = TEX.make_command('gloss');

  this.mainentry = TEX.make_command('mainentry');

  this.missing = TEX.make_command('missing');

  this.hbox = TEX.make_command('hbox');

  this.jzrplain = TEX.make_environment('jzrplain');

  this.tabular = TEX.make_environment('tabular');

  this.par = TEX.raw(' \\\\\n');

  this.hirabar = (TEX.make_loner('hirabar'))();

  this.next_cell = TEX.raw(' & ');

  this.new_page = (TEX.make_loner('clearpage'))();

  this._glyph_tag_from_chr_info = function(chr_info) {

    /* TAINT not well written */
    var rsg, tag, _ref;
    if (chr_info['csg'] === 'u' && (0x9fbc <= (_ref = chr_info['cid']) && _ref <= 0x9fcc)) {
      rsg = 'xxx';
    } else {
      rsg = chr_info['rsg'];
    }
    tag = this.glyph_tag_by_rsg[rsg];
    if (tag == null) {
      warn("unknown RSG " + (rpr(rsg)));
      return chr_info['chr'];
    }
    return tag(chr_info['chr']);
  };

  this.tag_from_chr = function(chr) {

    /* TAINT not well written */
    var chr_info, rsg;
    chr_info = CHR.analyze(chr, {
      input: 'xncr'
    });
    rsg = chr_info['rsg'];
    if (rsg === 'jzr-fig') {
      return TEX.raw("\\cnjzr{\\symbol{" + chr_info['cid'] + "}}");
    } else {
      return this._glyph_tag_from_chr_info(chr_info);
    }
  };

  this.py = function(text) {
    return this._py(this.raw(this._rewrite_pinyin(text)));
  };

  this._rewrite_pinyin = function(text) {
    var R;
    R = text;
    R = R.replace(/ǖ/, "\\upaccent{\\aboxshift{ˉ}}{ü}");
    R = R.replace(/ǘ/, "\\upaccent{\\aboxshift{´}}{ü}");
    R = R.replace(/ǚ/, "\\upaccent{\\aboxshift{ˇ}}{ü}");
    R = R.replace(/ǜ/, "\\upaccent{\\aboxshift{`}}{ü}");
    R = R.replace(/ê1/, "\\upaccent{\\aboxshift{ˉ}}{ê}");
    R = R.replace(/ê2/, "\\upaccent{\\aboxshift{´}}{ê}");
    R = R.replace(/ê3/, "\\upaccent{\\aboxshift{ˇ}}{ê}");
    R = R.replace(/ê4/, "\\upaccent{\\aboxshift{`}}{ê}");
    return R;
  };

  MULTIMIX = require('coffeenode-multimix');

  THIS = module.exports = MULTIMIX.compose(TEX, this);

  this.rpr = TEX.rpr.bind(TEX);

  THIS.postscript = THIS.raw(read(route_of_postscript));

  THIS.preamble = THIS.raw(read(route_of_preamble));

}).call(this);
